import { COLORS } from "@/constants/theme";
import { Dimensions, StyleSheet } from "react-native";

const { height } = Dimensions.get("window");
export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  safeArea: {
    flex: 1,
  },
  scrollContainer: {
    paddingHorizontal: 20,
    paddingBottom: 15,
  },
  progressSection: {
    marginBottom: 15,
  },
  // Level / Progress card (white card with level, progress bar, streak)
  levelCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
    flexDirection: "row",
    alignItems: "center",
    marginTop: 12,
  },
  levelCardTopRow: {
    flexDirection: "row",
    alignItems: "center",

  },
  levelBadge: {
    backgroundColor: "#E8ECF1",
    paddingHorizontal: 12,
    paddingVertical: 2,
    borderRadius: 999,
  },
  levelBadgeText: {
    fontSize: 14,
    fontWeight:"700",
    fontFamily: "Poppins-Bold",
    color: "#272d56",
  },
  levelCardDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: "#272d56",
    marginHorizontal: 6,
  },
  levelCardTitle: {
    fontSize: 14,
    fontFamily: "Poppins-Medium",
    color: "#272d56",
  },
  levelCardProgressRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  levelCardProgressBar: {
    flex: 1,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#E8ECF1",
    overflow: "hidden",
    marginRight: 10,
  },
  levelCardProgressFill: {
    height: "100%",
    borderRadius: 4,
    backgroundColor: COLORS.primary,
    width: "60%",
  },
  levelCardPercent: {
    fontSize: 16,
    fontFamily: "Poppins-Bold",
    color: "#272d56",
    marginRight: 12,
  },
  levelCardActionButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: COLORS.primary,
    justifyContent: "center",
    alignItems: "center",
  },
  levelCardStreakRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  levelCardStreakLabel: {
    fontSize: 14,
    fontFamily: "Poppins-Regular",
    color: "#272d56",
    marginRight: 4,
  },
  levelCardStreakValue: {
    fontSize: 14,
    fontFamily: "Poppins-Medium",
    color: "#E53E3E",
  },
  // Lanjut Belajar - Banner image
  lanjutBelajarBanner: {
    marginBottom: 20,
    borderRadius: 20,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 6,
  },
  lanjutBelajarBannerImage: {
    marginTop: 4,
    width: "100%",
    height: height * 0.1,
  },
  // Pilih Materi Belajar - section + 2x2 grid
  materiSection: {
    marginTop: 2,
  },
  materiSectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  materiSectionTitle: {
    fontFamily: "Poppins-Bold",
    fontSize: 16,
    color: "#2C3E50",
  },
  materiLihatSemua: {
    fontFamily: "Poppins-Medium",
    fontSize: 14,
    color: COLORS.primary,
  },
  materiGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  materiCard: {
    width: "48%",
    backgroundColor: "#FFFFFF",
    borderRadius: 14,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 4,
    padding: 8,
  },
  materiCardTop: {
    alignItems: "center",
    flex: 1,
    borderRadius: 6,
  },
  materiIconWrap: {
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    padding: 16,
  },
  materiCardIconImage: {
    width: 72,
    height: 72,
  },
  materiCardText: {
    flex: 1,
    justifyContent: "center",
    padding: 8,
    alignItems: "center",
  },
  materiCardTitle: {
    fontFamily: "Poppins-Bold",
    fontSize: 16,
    color: "#2C3E50",

  },
  materiCardSubtitle: {
    fontFamily: "Poppins-Regular",
    marginTop: -4,
    fontSize: 12,
    color: "#718096",
  },
  materiCardButton: {
    marginTop: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "#EDF2F7",
    width: "100%",
  },
  materiCardButtonLabel: {
    fontFamily: "Poppins-Medium",
    fontSize: 14,
  },
  materiArrowWrap: {
padding: 4,
    borderRadius: 200,
    justifyContent: "center",
    alignItems: "center",
  },
  // Lanjut Belajar CTA card (gradient blue, ilustrasi wanita keluar ke atas)
  lanjutBelajarCard: {
    marginBottom: 20,
    position: "relative",
    elevation: 6,
    minHeight: 100,
  },
  lanjutBelajarGradientWrap: {
    borderRadius: 20,
    overflow: "hidden",
    minHeight: 100,
  },
  lanjutBelajarGradient: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 18,
    paddingHorizontal: 18,
    minHeight: 100,
  },
  lanjutBelajarLeft: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
    marginRight: 90,
  },
  lanjutBelajarPlayIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "rgba(255,255,255,0.25)",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 14,
  },
  lanjutBelajarTextWrap: {
    flex: 1,
  },
  lanjutBelajarTitle: {
    color: "#FFFFFF",
    fontFamily: "Poppins-Bold",
    fontSize: 18,
  },
  lanjutBelajarSubtitle: {
    color: "#FFFFFF",
    fontFamily: "Poppins-Regular",
    fontSize: 13,
    opacity: 0.95,
  },
  lanjutBelajarIllustrationWrap: {
    position: "absolute",
    right: 12,
    bottom: 0,
    width: 120,
    height: 140,
    justifyContent: "flex-end",
    paddingHorizontal: 12,
    alignItems: "center",
  },
  lanjutBelajarIllustration: {
    width: 120,
    height: 140,
  },
  sectionTitle: {
    fontSize: 16,
    fontFamily: "Poppins-Bold",
    color: COLORS.primarydark,
    marginBottom: 12,
  },
  overallProgressCard: {
    backgroundColor: "#16213e",
    borderRadius: 20,
    padding: 20,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#2a2d47",
  },
  progressInfo: {
    flex: 1,
  },
  progressTitle: {
    fontSize: 16,
    fontFamily: "Poppins-Bold",
    color: "#ffffff",
    marginBottom: 4,
  },
  progressSubtitle: {
    fontSize: 14,
    color: "#a0a0b8",
  },
  circularProgress: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: "#2a2d47",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 3,
    borderColor: "#4facfe",
  },
  progressPercentage: {
    fontSize: 16,
    fontFamily: "Poppins-Bold",
    color: "#4facfe",
  },
  modulesSection: {
    marginBottom: 20,
    marginTop: 0,
  },
  modulesGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    gap: 8,
  },
  quickActionsSection: {
    marginBottom: 15,
  },
  quickActions: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  quickActionCard: {
    backgroundColor: "#16213e",
    borderRadius: 16,
    padding: 16,
    alignItems: "center",
    flex: 1,
    marginHorizontal: 4,
    borderWidth: 1,
    borderColor: "#2a2d47",
  },
  quickActionIcon: {
    fontSize: 24,
    marginBottom: 8,
  },
  quickActionText: {
    fontSize: 12,
    color: "#a0a0b8",
    textAlign: "center",
  },
  footer: {
    alignItems: "center",
    paddingVertical: 10,
  },
  footerText: {
    fontSize: 14,
    color: "#6b6b83",
    textAlign: "center",
  },
  featuredImageContainer: {
    width: "100%",
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  featuredImage: {
    width: 100,
    height: 100,
  },
  moduleTitle: {
    marginTop: -4,
    fontSize: 12,
    fontFamily: "Poppins-Bold",
    color: COLORS.primarydark,
    marginBottom: 2,
    textAlign: "left",
  },
  moduleSubtitle: {
    fontSize: 10,
    fontFamily: "Poppins-Regular",
    color: "#a0a0b8",
    marginBottom: 0,
    textAlign: "left",
  },
  startButton: {
    backgroundColor: "#192a56",
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    marginTop: 6,
    width: "100%",
    alignItems: "center",
    shadowColor: "#005c97",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  startButtonText: {
    color: "#ffffff",
    fontSize: 12,
    fontFamily: "Poppins-Bold",
  },
  // Carousel styles
  carouselSection: {
    marginBottom: 12,
  },
  carousel: {
    alignSelf: "center",
  },
  carouselItem: {
    width: "97%",
    borderRadius: 16,
    padding: 16,
    height: 178,
    marginHorizontal: 8,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  carouselContent: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
    justifyContent: "space-between",
  },
  carouselLeftSection: {
    width: "68%",
    paddingRight: 16,
  },
  carouselRightSection: {
    position: "absolute",
    right: -32,
    bottom: -36,
    alignItems: "center",
    justifyContent: "center",
  },
  carouselBookIcon: {
    fontSize: 24,
    marginBottom: 8,
    position: "absolute",
    top: -8,
    left: 0,
  },
  carouselTextContainer: {
    flex: 1,
  },
  bannerPersonImage: {
    width: 160,
    height: 200,
  },
  carouselTitle: {
    fontSize: 18,
    fontFamily: "Poppins-Bold",
    marginBottom: 4,
  },
  carouselSubtitle: {
    fontSize: 9,
    lineHeight: 16,
  },
  carouselCTA: {
    backgroundColor: "#FF8C00",
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 25,
    marginTop: 12,
    alignSelf: "flex-start",
    shadowColor: "#FF8C00",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  carouselCTAText: {
    color: "#ffffff",
    fontSize: 10,
    fontFamily: "Poppins-Bold",
  },
  // Custom Header styles
  customHeader: {

    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  headerLeft: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },
  avatarContainer: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: COLORS.primarydark,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  foxAvatar: {
    fontSize: 24,
  },
  titleContainer: {
    flex: 1,
  },
  headerTitle: {
    fontSize: 18,
    fontFamily: "Poppins-Bold",
    marginBottom: 2,
  },
  headerSubtitle: {
    marginTop: -8,
    fontSize: 12,
    fontFamily: "Poppins-Regular",
    color: COLORS.primarydark,
  },
  settingsButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COLORS.card,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  settingsIcon: {
    fontSize: 20,
  },
  headerAvatarButton: {

    borderRadius: 21,
    backgroundColor: "white",
    padding: 1,
  },
  headerAvatar: {
    width: 42,
    height: 42,
    borderRadius: 21,
  },
  // Empty State styles
  emptyStateBinderCard: {
    width: "100%",
    minHeight: 220,
    paddingVertical: 24,
    paddingHorizontal: 16,
    justifyContent: "center",
    alignItems: "center",
  },
  emptyStateContainer: {
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: "grey",
    borderRadius: 12,
    backgroundColor: "red",
    marginHorizontal: 24,
    flex: 1,
  },
  emptyStateImage: {
    width: 180,
    height: 180,
    marginBottom: 16,
    alignSelf: "center",
  },
  lottieContainer: {
    width: 180,
    height: 180,
    justifyContent: "center",
    alignItems: "center",
    alignSelf: "center",
    marginBottom: 16,
  },
  emptyStateTitle: {
    fontSize: 16,
    fontFamily: "Poppins-Bold",
    textAlign: "center",
    marginBottom: 8,
    alignSelf: "center",
  },
  emptyStateSubtitle: {
    fontSize: 14,
    fontFamily: "Poppins-Regular",
    textAlign: "center",
    lineHeight: 20,
    color: COLORS.textSecondary,
    paddingHorizontal: 12,
    marginBottom: 16,
    alignSelf: "center",
  },
  emptyStateButton: {
    backgroundColor: COLORS.primarydark,
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 25,
    shadowColor: "#005c97",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
    alignSelf: "stretch",
    alignItems: "center",
  },
  emptyStateButtonText: {
    color: "#ffffff",
    fontSize: 14,
    fontFamily: "Poppins-Bold",
  },
});
